alter table typing_runs
  add constraint typing_runs_calibration_wpm_range check (calibration_wpm is null or calibration_wpm between 0 and 250),
  add constraint typing_runs_calibration_bin_range check (calibration_bin_index is null or calibration_bin_index between 0 and 20),
  add constraint typing_runs_target_load_range check (target_load is null or target_load between 0 and 2),
  add constraint typing_runs_arrival_rate_range check (arrival_rate is null or arrival_rate between 0 and 20),
  add constraint typing_runs_expected_arrivals_range check (expected_arrivals is null or expected_arrivals between 0 and 1000),
  add constraint typing_runs_arrival_count_range check (arrival_count is null or arrival_count between 0 and 1000),
  add constraint typing_runs_completed_count_range check (completed_count is null or completed_count between 0 and 1000),
  add constraint typing_runs_observed_arrival_rate_range check (observed_arrival_rate is null or observed_arrival_rate between 0 and 20),
  add constraint typing_runs_throughput_per_second_range check (throughput_per_second is null or throughput_per_second between 0 and 20),
  add constraint typing_runs_avg_response_range check (avg_response_ms is null or avg_response_ms between 0 and 600000),
  add constraint typing_runs_avg_service_range check (avg_service_demand_ms is null or avg_service_demand_ms between 0 and 600000),
  add constraint typing_runs_avg_typing_wpm_range check (avg_typing_wpm is null or avg_typing_wpm between 0 and 300),
  add constraint typing_runs_reaction_range check (reaction_ms is null or reaction_ms between 0 and 60000),
  add constraint typing_runs_utilization_range check (utilization is null or utilization between 0 and 100),
  add constraint typing_runs_avg_queue_range check (avg_queue_length is null or avg_queue_length between 0 and 1000),
  add constraint typing_runs_max_queue_range check (max_queue_length is null or max_queue_length between 0 and 1000),
  add constraint typing_runs_still_waiting_range check (still_waiting_count is null or still_waiting_count between 0 and 1000),
  add constraint typing_runs_duration_range check (duration_ms is null or duration_ms between 1000 and 600000),
  add constraint typing_runs_service_estimate_range check (service_demand_estimate_ms is null or service_demand_estimate_ms between 0 and 600000),
  add constraint typing_runs_reference_response_range check (reference_response_ms is null or reference_response_ms between 0 and 600000),
  add constraint typing_runs_seed_range check (seed is null or seed between 0 and 2147483647),
  add constraint typing_runs_difficulty_key_allowed check (difficulty_key in ('easy', 'medium', 'hard', 'impossible'));
